var express = require('express');
var router = express.Router();

router.get('/srt', function(req, res){
    document.write( '<!DOCTYPE html>\n' );
    document.write( '<html>\n' );
    document.write( '  <head>\n' );
    document.write( '    <meta charset=\"utf-8\">\n' );
    document.write( '    <script src=\"https://code.jquery.com/jquery-1.12.4.js\" integrity=\"sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=\" crossorigin=\"anonymous\"></script>\n' );
    document.write( '    <script src=\"/assets/js/jquery.min.js\"></script>\n' );
    document.write( '    <script src=\"/assets/bootstrap/js/bootstrap.min.js\"></script>\n' );
    document.write( '    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n' );
    document.write( '    <title>UploadSong</title>\n' );
    document.write( '    <link rel=\"stylesheet\" href=\"/assets/bootstrap/css/bootstrap.min.css\">\n' );
    document.write( '    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Cookie\">\n' );
    document.write( '    <link rel=\"stylesheet\" href=\" /assets/fonts/font-awesome.min.css\">\n' );
    document.write( '    <link rel=\"stylesheet\" href=\" /assets/css/styles.css\">\n' );
    document.write( '    <link rel=\"stylesheet\" href=\" /assets/css/Pretty-Header.css\">\n' );
    document.write( '    <link rel=\"stylesheet\" href=\" /assets/css/Pretty-Footer.css\">\n' );
    document.write( '    <link rel=\"stylesheet\" href=\" /assets/css/Pretty-Registration-Form.css\">\n' );
    document.write( '  </head>\n' );
    document.write( '  <body>\n' );
    document.write( '    <nav class=\"navbar navbar-default custom-header\">\n' );
    document.write( '      <div class=\"container-fluid\">\n' );
    document.write( '        <div class=\"navbar-header\">\n' );
    document.write( '          <before></before><a class=\"navbar-brand navbar-link\" href=\"#\">\n' );
    document.write( '            <p>Companylogo</p></a>\n' );
    document.write( '          <button class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar-collapse\"><span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button>\n' );
    document.write( '        </div>\n' );
    document.write( '        <div class=\"collapse navbar-collapse\" id=\"navbar-collapse\">\n' );
    document.write( '          <ul class=\"nav navbar-nav links\">\n' );
    document.write( '            <li role=\"presentation\"><a href=\"#\">Overview </a></li>\n' );
    document.write( '            <li role=\"presentation\"><a href=\"#\">Surveys </a></li>\n' );
    document.write( '            <li role=\"presentation\"><a href=\"#\"> Reports</a></li>\n' );
    document.write( '            <li role=\"presentation\"><a class=\"custom-navbar\" href=\"#\">Roles<span class=\"badge\">new</span></a></li>\n' );
    document.write( '          </ul>\n' );
    document.write( '          <ul class=\"nav navbar-nav navbar-right\">\n' );
    document.write( '            <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\" href=\"#\"><span class=\"caret\"></span><img class=\"dropdown-image\" src=\" /assets/img/avatar.jpg\"></a>\n' );
    document.write( '              <ul class=\"dropdown-menu dropdown-menu-right\" role=\"menu\">\n' );
    document.write( '                <li role=\"presentation\"><a href=\"#\">Settings </a></li>\n' );
    document.write( '                <li role=\"presentation\"><a href=\"#\">Payments </a></li>\n' );
    document.write( '                <li class=\"active\" role=\"presentation\"><a href=\"#\">Logout </a></li>\n' );
    document.write( '              </ul>\n' );
    document.write( '            </li>\n' );
    document.write( '          </ul>\n' );
    document.write( '        </div>\n' );
    document.write( '      </div>\n' );
    document.write( '    </nav>\n' );
    document.write( '    <div class=\"row register-form\">\n' );
    document.write( '      <div class=\"col-md-8 col-md-offset-2\">\n' );
    document.write( '        <form class=\"form-horizontal custom-form\" action=\"/listsongs\" method=\"post\" enctype=\"multipar/form-data\">\n' );
    document.write( '          <h1>Upload</h1><br>\n' );
    document.write( '          <label> Name of the song</label>\n' );
    document.write( '          <input class=\"form-control\" type=\"text\" name=\"SongName\" required><br>\n' );
    document.write( '          <label>Artist </label>\n' );
    document.write( '          <input class=\"form-control\" type=\"text\" name=\"Artist\" required><br>\n' );
    document.write( '          <label>browse song</label>\n' );
    document.write( '          <input type=\"file\" name=\"audiofile\" required>\n' );
    document.write( '          <button class=\"btn btn-default submit-button\" type=\"submit\">Add Song</button>\n' );
    document.write( '        </form>\n' );
    document.write( '      </div>\n' );
    document.write( '    </div>\n' );
    document.write( '    <footer>\n' );
    document.write( '      <div class=\"row\">\n' );
    document.write( '        <div class=\"col-md-4 col-sm-6 footer-navigation\">\n' );
    document.write( '          <h3><a href=\"#\">Company<span>logo                    </span></a></h3>\n' );
    document.write( '          <p class=\"links\"><a href=\"#\">Home</a><strong> · </strong><a href=\"#\">Blog</a><strong> · </strong><a href=\"#\">Pricing</a><strong> · </strong><a href=\"#\">About</a><strong> · </strong><a href=\"#\">Faq</a><strong> · </strong><a href=\"#\">Contact</a></p>\n' );
    document.write( '          <p class=\"company-name\">Company Name © 2015 </p>\n' );
    document.write( '        </div>\n' );
    document.write( '        <div class=\"col-md-4 col-sm-6 footer-contacts\">\n' );
    document.write( '          <div><span class=\"fa fa-map-marker footer-contacts-icon\"> </span>\n' );
    document.write( '            <p><span class=\"new-line-span\">21 Revolution Street</span><span>Paris, France</span></p>\n' );
    document.write( '          </div>\n' );
    document.write( '          <div><i class=\"fa fa-phone footer-contacts-icon\"></i>\n' );
    document.write( '            <p class=\"footer-center-info email text-left\"> +1 555 123456</p>\n' );
    document.write( '          </div>\n' );
    document.write( '          <div><i class=\"fa fa-envelope footer-contacts-icon\"></i>\n' );
    document.write( '            <p><a href=\"#\" target=\"_blank\">support@company.com</a></p>\n' );
    document.write( '          </div>\n' );
    document.write( '        </div>\n' );
    document.write( '        <div class=\"clearfix visible-sm-block\"></div>\n' );
    document.write( '        <div class=\"col-md-4 footer-about\">\n' );
    document.write( '          <h4>About the company</h4>\n' );
    document.write( '          <p>\n' );
    document.write( '            <Lorem>ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet.</Lorem>\n' );
    document.write( '          </p>\n' );
    document.write( '          <div class=\"social-links social-icons\"><a href=\"#\"><i class=\"fa fa-facebook\"></i></a><a href=\"#\"><i class=\"fa fa-twitter\"></i></a><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a><a href=\"#\"><i class=\"fa fa-github\"></i></a></div>\n' );
    document.write( '        </div>\n' );
    document.write( '      </div>\n' );
    document.write( '    </footer>\n' );
    document.write( '  </body>\n' );
    document.write( '</html>' );
    
    return res.end();
});
module.exports=router;